version: "3.9"
services:
  api:
    build: ./WebApi
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: "marko"
      MYSQL_PASSWORD: "password"
      MYSQL_SERVER: "mysql"
  mysql:
    build: ./database
